apiVersion: apps/v1
kind: Deployment
metadata:
  name: inkops-ui
  labels:
    app: inkops-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inkops-ui
  template:
    metadata:
      labels:
        app: inkops-ui
    spec:
      containers:
        - name: inkops-ui
          image: inkops-ui:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
