deployment:
  name: octant-ui
  replicas: 1
  containerPort: 8080
  tolerations: []
  nodeSelector: {}
  affinity: {}
  annotations: {}
  gateway_host: http://mdai-gateway.mdai.svc.cluster.local:8081

image:
  repository: public.ecr.aws/decisiveai/octant-ui
  # tag: 0.0.1

service:
  name: octant-ui
  replicas: 1
  port: 8080
  targetPort: 8080
  type: ClusterIP
