name: Docker push for main branch

on:
  workflow_dispatch:

jobs:
  stub:
      runs-on: ubuntu-latest
      steps:
      - run: echo "I am a dummy flow that exists to get around Github Actions limitations around testing workflows not on main from the gh cli"