# https://github.com/anothrNick/github-tag-action#bumping
# Controlling the patch, minor, major version bump can be done manually with a special tag in your merge commit message.
name: Bump semantic version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

env:
  REPO_ORGANIZATION: "MyDecisive"
  OCTANT_REPO: "octant"

jobs:
  gh-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'  # 0 is needed to get all tags
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch # Options: major, minor, patch, none
  docker-tag:
    needs: gh-tag
    if: needs.gh-tag.outputs.new_tag != ''
    uses: MyDecisive/ci/.github/workflows/docker-ghcr.yaml@main
    with:
      ref: refs/tags/${{ needs.gh-tag.outputs.new_tag }}
    secrets: inherit # pass all secrets
  helm-publish:
    needs: [gh-tag, docker-tag]
    if: needs.gh-tag.outputs.new_tag != ''
    uses: MyDecisive/ci/.github/workflows/helm-publish.yml@main
    with:
      ref: refs/tags/${{ needs.gh-tag.outputs.new_tag }}
    secrets: inherit # pass all secrets
  trigger-octant:
    needs: [gh-tag, docker-tag]
    name: Trigger Octant Build
    if: needs.gh-tag.outputs.new_tag != ''
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.INTERNAL_WRITE_ACCESS_GH_APP_ID }}
          private-key: ${{ secrets.INTERNAL_WRITE_ACCESS_GH_APP_PRIVATE_KEY }}
          owner: ${{ env.REPO_ORGANIZATION }}
          repositories: ${{ env.OCTANT_REPO }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.REPO_ORGANIZATION }}/${{ env.OCTANT_REPO }}
          event-type: build-and-publish
          client-payload: '{"ui-ver": "${{needs.gh-tag.outputs.new_tag }}"}'
